### ISSUE TITLE
Freeing dynamically allocated values

### ISSUE THREAD

**Issue by weshoke** [preshing/junction#11] opened 2016-05-04 04:00 UTC
How do you free dynamically allocated values when, for example, SingleMap_Linear is destroyed.  I see that the cell's destructors are run, but that doesn't free the Value if the Value is a pointer.  And without a way to iterate over entries, it seems there would just me a memory leak.

**Comment by preshing** [comment] 2016-05-09 00:20
Currently you need to iterate over the items and free them yourself, which I admit is not too friendly, and as you point out, the iterator is missing from SingleMap_Linear.

**Comment by abhinav04sharma** [comment] 2017-11-10 20:24
There is another problem with dynamically allocated values. Since, erase() doesn't call free/delete the application has to deallocate the memory manually, this can cause race condition between threads. Consider the following sequence of events for example:
value= get(key) [thread 1] -> value= erase(key) [thread 2] ->delete value [thread 2] -> use value somehow [thread 1]

Here thread 1 will end up using deallocated memory. Ideally, there should be a way to specify a deallocation callback which is called atomically within erase().

**Comment by preshing** [comment] 2017-11-12 00:21
@abhinav04sharma Thanks for the input, but your example is flawed. You're deleting a value that's in use by thread 1. It's never safe for an application to destroy some data that's still in use by other threads. This has nothing to do with the design of the map. In particular, your example wouldn't be any safer if the map called delete inside erase() for you (which is what you seem to propose).

I like leaving it up to the application to decide how and when to destroy values (if at all) after erasing them from the map.

**Comment by preshing** [comment] 2017-11-12 00:24
Note that this issue is only open as a reminder that the iterator is still missing from SingleMap_Linear.

**Comment by preshing** [comment] 2017-11-12 00:26
Actually that's already covered by issue #10. Closing this as a duplicate.

**Closed by preshing** 2017-11-12 00:26 UTC

**Comment by abhinav04sharma** [comment] 2017-11-14 00:57
@preshing leaving the application to destroy values is usually okay but with RAII any container is expected to call the destructor of element. In fact, std::map (and it's variants), tbb etc. all call destructors of the key and the value type when an entry is erased. Since junction's maps only support integers as keys and values, memory management can become a hassle because we now have to store pointers to dynamically allocated objects instead of the object itself (or an object pointer wrapped around a shared_ptr). In my example, the only ways I can think of to fix the problem is either to use locks to protect the pointer (which defeats the purpose of using a lock free structure) or to use some form of QSBR. Now, since QSBR is already done by junction itself, it would be much more convenient to specify a callback function which the library can call after deallocating a cell (note that I'm not completely familiar with how this will work, I only have a general idea).

**Comment by preshing** [comment] 2017-11-14 01:43
I agree that it would sometimes be convenient to have a Junction map that destroys objects for you. But it wouldn't make your example safer.

Put it this way: Imagine we aren't even talking about maps. There's no map. There's just a single atomic<> pointer to a dynamically allocated object. Now look at your example again. It's basically just "Thread 2 destroys object, then Thread 1 attemps to use it." That's just a recipe for a crash. A mutex (lock) won't help you here in any way, since atomicity is not the problem. The problem is lifetime management. You simply need to manage your object lifetimes properly at the application level. Don't destroy an object until you are certain that all threads are finished with it and will never attempt to use it again. This goes for anything in concurrency, not just maps.

Lifetime management can actually be quite simple, or it can be really complex, depending on the application. In complex cases where objects have no clear owner, reference counting is perhaps the simplest solution. But again, it has nothing to do with Junction maps.

**Comment by abhinav04sharma** [comment] 2017-11-14 20:39
@preshing RAII is the simplest form for lifecycle management :) With RAII the owner of the object is responsible to destroying it and all containers have the ability to transferring ownership of objects into and out of themselves. That is what I think is missing in junction maps. As I said (and you confirmed in your previous comment), two ways to solving this without RAII is to use locks (which completely defeats the purpose of using lock free structures in the first place) or, like you said: "Don't destroy an object until you are certain that all threads are finished with it and will never attempt to use it again" which is what QSBR essentially does. By asking junction maps to delete the object for me I'm essentially transferring the objects ownership to it.

**Comment by brucejee** [comment] 2022-08-10 02:02
I have the same problem, i think map support shared_ptr<V> value will fix the problem, like this: ```ConcurrentMap_Leapfrog<int, shared_ptr<V>>```，and [```std::atomic<std::shared_ptr<V>>```](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic2) only support since C++20.
